### ISSUE TITLE
crops and some sapling cant work

### ISSUE THREAD

**Issue by xly2000** [LothrazarMinecraftMods/SaplingGrowthControl#1]
all crops? maybe

sapling:
		biomesoplenty:bayou#
		biomesoplenty:bog#biomesoplenty:sapling_2:3	

tree grow in bayou not bog

**Comment by Lothrazar** [comment]
Mad has been mostly re-written for 1.16+ https://www.curseforge.com/minecraft/mc-mods/restricted-saplings/files/3203020
