### ISSUE TITLE
does not load on server

### ISSUE THREAD

**Issue by maradotwebp** [LothrazarMinecraftMods/SaplingGrowthControl#6]
Minecraft Version: 1.16.4

Forge Version: 35.1.37

Mod Version: 1.0.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Mod does not load at all on Server.
Judging from the code, it's because the mod hasn't been written with the server in mind.

Log file link:
[latest.log](https://github.com/Lothrazar/SaplingGrowthControl/files/5920890/latest.log)

**Comment by Lothrazar** [comment]
Thanks, got a fix out https://www.curseforge.com/minecraft/mc-mods/restricted-saplings/files/3203020
